{{- if .Values.AlertmanagerSNSForwarder.enabled -}}
# see https://github.com/DataReply/alertmanager-sns-forwarder for docs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.AlertmanagerSNSForwarder.IamRole }}
  name: alertmanager-sns-forwarder
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alertmanager-sns-forwarder
  labels:
    component: alertmanager-sns-forwarder
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: alertmanager-sns-forwarder
    spec:
      serviceAccountName: alertmanager-sns-forwarder
      restartPolicy: Always
      containers:
      - name: alertmanager-sns-forwarder
        #image compiled from https://github.com/dbonfigli/alertmanager-sns-forwarder
        #the original repo is not updated with the latest aws sdk, so it does not work with iam authentication via oidc
        image: dbonfigli/alertmanager-sns-forwarder:0.2
        env:
          - name: AWS_REGION
            value: "{{.Values.AlertmanagerSNSForwarder.region}}"
          - name: AWS_DEFAULT_REGION
            value: "{{.Values.AlertmanagerSNSForwarder.region}}"
          - name: SNS_FORWARDER_ARN_PREFIX
            value: "{{.Values.AlertmanagerSNSForwarder.arnPrefix}}"
          - name: SNS_FORWARDER_DEBUG
            value: "{{.Values.AlertmanagerSNSForwarder.debug}}"
        resources:
          limits:
            memory: 1Gi
            cpu: 0.5
          requests:
            cpu: 0.2
            memory: 0.5Gi
        ports:
          - containerPort: 9087
            name: webhook-port
        livenessProbe:
          httpGet:
            path: /health
            port: webhook-port
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: webhook-port
          initialDelaySeconds: 10
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-sns-forwarder-svc
  labels:
    component:  alertmanager-sns-forwarder
spec:
  ports:
    - port: 9087
      name: webhook-port
  selector:
    component: alertmanager-sns-forwarder
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: alertmanager-sns-forwarder-metrics-sm
#   namespace: default
#   labels:
#     component: alertmanager-sns-forwarder
# spec:
#   selector:
#     component: alertmanager-sns-forwarder
#   endpoints:
#   - port: webhook-port
#     scrapeTimeout: "30s"
#     interval: "40s"
{{- end }}