apiVersion: v2
name: monitoring
description: monitoring of application
type: application
version: 1.1
appVersion: 1

dependencies:
- name: prometheus-operator
  repository: https://charts.bitnami.com/bitnami
  version: 0.14
- name: grafana
  repository: https://charts.bitnami.com/bitnami
  version: 1.4.1
  condition: grafana.enabled

# helm docs at:
# - https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator/
# with explanations at:
# - https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md
# grafana:
# - https://github.com/bitnami/charts/tree/master/bitnami/grafana